[package]
name = "vellum"
version = "0.1.0"
edition = "2024"
description = "Records the history of commands run"

[dependencies]
clap = { version = "4.5.35", features = ["derive", "unicode", "wrap_help"] }
clap-cargo = "0.15.2"
env_logger = "0.11.8"
fork = "0.2.0"
hostname = "0.4.1"
log = { version = "0.4.27", features = ["std", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
xdg = { version = "2.5.2", features = ["serde"] }
